import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '../shared/theme-provider'
import { LangSwitcher } from '../shared/lang-switcher'
import { ThemeSwitcher } from '../shared/theme-switcher'
import { cookies } from 'next/headers'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    // Читаем тему из cookie на сервере
    const cookieStore = await cookies()
    const theme = cookieStore.get('theme')?.value === 'dark' ? 'dark' : 'light'

    return (
        <html lang="ru" className={theme}>
            <head />
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider initialTheme={theme}>
                    <header className="mb-4 flex items-center justify-between border-b p-4">
                        <div className="text-lg font-bold">JobFinder</div>
                        <div className="flex gap-4">
                            <LangSwitcher />
                            <ThemeSwitcher />
                        </div>
                    </header>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    )
}

/**
 * Layout с ThemeProvider, переключателями темы и языка
 */
